- name: restart postgres
  service: name=postgresql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes

- name: restart app
  service: name={{ app_name }} state=restarted enabled=yes
  become: yes
  
- name: restart supervisord
  command: service supervisord restart
  become: yes

- name: reload pf
  command: pfctl -f /etc/pf.conf
  become: yes