# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20170228_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='songs.Tag'),
        ),
    ]
