# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20170228_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
