# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20170301_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
