# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:06
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20170302_0748'),
    ]

    operations = [
        TrigramExtension(),
    ]
