# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20170302_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongUpdateToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_started', models.DateField()),
                ('last_finished', models.DateField()),
            ],
        ),
    ]
