# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_auto_20170309_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='songupdatetoken',
            name='song_count',
            field=models.IntegerField(null=True),
        ),
    ]
