##
# Configure the server for the Django app
##
- include: 01_server.yml
- include: 02_git.yml
- include: 03_postgres.yml
- include: 04_redis.yml
- include: 05_dependencies.yml
- include: 06_migrations.yml
- include: 07_nginx.yml
- include: 08_gunicorn.yml
- include: 09_supervisor.yml
- include: 10_rc_init_script.yml

