#!/bin/bash

### Define script variables

# Name of the app
NAME='{{ app_name }}'

# Path to virtualenv
VIRTUALENV='{{ venv_dir }}'
GUNICORN='{{ venv_dir }}/bin/gunicorn'

# Django Project Directory
DJANGODIR='{{ app_dir }}'

# The user to run as
USER='{{ deployer_user }}'

# Number of worker processes Gunicorn should spawn
NUM_WORKERS=3
# Settings file that Gunicorn should use
DJANGO_SETTINGS_MODULE={{ django_settings_module }}
# WSGI module name
DJANGO_WSGI_MODULE={{ django_wsgi_module }}


### Activate virtualenv and create environment variables

echo "Starting $NAME as `whoami`"
# Activate the virtual environment
cd $VIRTUALENV
. bin/activate
. $DJANGODIR/.env

# Defining the Environment Variables
export DATABASE_URL='{{ db_url }}'
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

### Start Gunicorn
exec ${GUNICORN} ${DJANGO_WSGI_MODULE}:application \
        --name $NAME \
        --workers $NUM_WORKERS \
        --user=$USER\
        --log-level=debug \
        --bind=127.0.0.1:8000